version: '3.1'

services:
  test:
    build: .
    command: ["go", "test", "-v", "./..."]
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://migrate:migrate@postgres:5432/test_migrations
      RUN_MIGRATIONS: "YES"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: migrate
      POSTGRES_PASSWORD: migrate
      POSTGRES_DB: test_migrations
